language: php

sudo: false

php:
  - 7.1
  - 7.2

env:
  global:
    - setup=basic
    - coverage=no
  matrix:
    - laravel=5.6.*
    - laravel=5.7.*
    - laravel=dev-master

before_script:
  - composer config discard-changes true
  - if [[ $setup = 'basic' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit

matrix:
  include:
    - php: 7.1
      env:
        - setup=lowest
        - laravel=5.6.*
    - php: 7.1
      env:
        - setup=basic
        - laravel=5.6.*
    - php: 7.1
      env:
        - setup=stable
        - laravel=5.6.*
    - php: 7.1
      env:
        - setup=lowest
        - laravel=5.7.*
    - php: 7.1
      env:
        - setup=basic
        - laravel=5.7.*
    - php: 7.1
      env:
        - setup=stable
        - laravel=5.7.*
  allow_failures:
    - env: laravel=dev-master
  fast_finish: true
